apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod9
  labels:
    name: pod9
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod9
  template:
    metadata:
      labels:
        name: pod9
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.244.246.137\"]"
    spec:
      restartPolicy: Always
      containers:
        - name: receiver
          image: pod9:latest
          imagePullPolicy: Never
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
